class KeyEnum {

  static const RESERVED = KeyEnum(0, 0);
  static const keyA = KeyEnum(4, 30);
  static const keyAShift = KeyEnum(4, 30, true);
  static const keyB = KeyEnum(5, 48);
  static const keyBShift = KeyEnum(5, 48, true);
  static const keyC = KeyEnum(6, 46);
  static const keyCShift = KeyEnum(6, 46, true);
  static const keyD = KeyEnum(7, 32);
  static const keyDShift = KeyEnum(7, 32, true);
  static const keyE = KeyEnum(8, 18);
  static const keyEShift = KeyEnum(8, 18, true);
  static const keyF = KeyEnum(9, 33);
  static const keyFShift = KeyEnum(9, 33, true);
  static const keyG = KeyEnum(10, 34);
  static const keyGShift = KeyEnum(10, 34, true);
  static const keyH = KeyEnum(11, 35);
  static const keyHShift = KeyEnum(11, 35, true);
  static const keyI = KeyEnum(12, 23);
  static const keyIShift = KeyEnum(12, 23, true);
  static const keyJ = KeyEnum(13, 36);
  static const keyJShift = KeyEnum(13, 36, true);
  static const keyK = KeyEnum(14, 37);
  static const keyKShift = KeyEnum(14, 37, true);
  static const keyL = KeyEnum(15, 38);
  static const keyLShift = KeyEnum(15, 38, true);
  static const keyM = KeyEnum(16, 50);
  static const keyMShift = KeyEnum(16, 50, true);
  static const keyN = KeyEnum(17, 49);
  static const keyNShift = KeyEnum(17, 49, true);
  static const keyO = KeyEnum(18, 24);
  static const keyOShift = KeyEnum(18, 24, true);
  static const keyP = KeyEnum(19, 25);
  static const keyPShift = KeyEnum(19, 25, true);
  static const keyQ = KeyEnum(20, 16);
  static const keyQShift = KeyEnum(20, 16, true);
  static const keyR = KeyEnum(21, 19);
  static const keyRShift = KeyEnum(21, 19, true);
  static const keyS = KeyEnum(22, 31);
  static const keySShift = KeyEnum(22, 31, true);
  static const keyT = KeyEnum(23, 20);
  static const keyTShift = KeyEnum(23, 20, true);
  static const keyU = KeyEnum(24, 22);
  static const keyUShift = KeyEnum(24, 22, true);
  static const keyV = KeyEnum(25, 47);
  static const keyVShift = KeyEnum(25, 47, true);
  static const keyW = KeyEnum(26, 17);
  static const keyWShift = KeyEnum(26, 17, true);
  static const keyX = KeyEnum(27, 45);
  static const keyXShift = KeyEnum(27, 45, true);
  static const keyY = KeyEnum(28, 21);
  static const keyYShift = KeyEnum(28, 21, true);
  static const keyZ = KeyEnum(29, 44);
  static const keyZShift = KeyEnum(29, 44, true);
  static const key1 = KeyEnum(30, 2);
  static const key1Shift = KeyEnum(30, 2, true);
  static const key2 = KeyEnum(31, 3);
  static const key2Shift = KeyEnum(31, 3, true);
  static const key3 = KeyEnum(32, 4);
  static const key3Shift = KeyEnum(32, 4, true);
  static const key4 = KeyEnum(33, 5);
  static const key4Shift = KeyEnum(33, 5, true);
  static const key5 = KeyEnum(34, 6);
  static const key5Shift = KeyEnum(34, 6, true);
  static const key6 = KeyEnum(35, 7);
  static const key6Shift = KeyEnum(35, 7, true);
  static const key7 = KeyEnum(36, 8);
  static const key7Shift = KeyEnum(36, 8, true);
  static const key8 = KeyEnum(37, 9);
  static const key8Shift = KeyEnum(37, 9, true);
  static const key9 = KeyEnum(38, 10);
  static const key9Shift = KeyEnum(38, 10, true);
  static const key0 = KeyEnum(39, 11);
  static const key0Shift = KeyEnum(39, 11, true);
  static const keyEnter = KeyEnum(40, 28);
  static const keyEsc = KeyEnum(41, 1);
  static const keyBackspace = KeyEnum(42, 14);
  static const keyTab = KeyEnum(43, 15);
  static const keySpace = KeyEnum(44, 57);
  static const keyMinus = KeyEnum(45, 12);
  static const keyMinusShift = KeyEnum(45, 12, true);
  static const keyEqual = KeyEnum(46, 13);
  static const keyEqualShift = KeyEnum(46, 13, true);
  static const keyLeftbrace = KeyEnum(47, 26);
  static const keyLeftbraceShift = KeyEnum(47, 26, true);
  static const keyRightbrace = KeyEnum(48, 27);
  static const keyRightbraceShift = KeyEnum(48, 27, true);
  static const keyBackslash = KeyEnum(49, 43);
  static const keyBackslashShift = KeyEnum(49, 43, true);
  static const keySemicolon = KeyEnum(51, 39);
  static const keySemicolonShift = KeyEnum(51, 39, true);
  static const keyApostrophe = KeyEnum(52, 40);
  static const keyApostropheShift = KeyEnum(52, 40, true);
  static const keyGrave = KeyEnum(53, 41);
  static const keyGraveShift = KeyEnum(53, 41, true);
  static const keyComma = KeyEnum(54, 51);
  static const keyCommaShift = KeyEnum(54, 51, true);
  static const keyDot = KeyEnum(55, 52);
  static const keyDotShift = KeyEnum(55, 52, true);
  static const keySlash = KeyEnum(56, 53);
  static const keySlashShift = KeyEnum(56, 53, true);
  static const keyCapslock = KeyEnum(57, 58);
  static const keyF1 = KeyEnum(58, 59);
  static const keyF2 = KeyEnum(59, 60);
  static const keyF3 = KeyEnum(60, 61);
  static const keyF4 = KeyEnum(61, 62);
  static const keyF5 = KeyEnum(62, 63);
  static const keyF6 = KeyEnum(63, 64);
  static const keyF7 = KeyEnum(64, 65);
  static const keyF8 = KeyEnum(65, 66);
  static const keyF9 = KeyEnum(66, 67);
  static const keyF10 = KeyEnum(67, 68);
  static const keyF11 = KeyEnum(68, 87);
  static const keyF12 = KeyEnum(69, 88);
  static const keySysrq = KeyEnum(70, 99); // Is this Print Screen?
  static const keyScrolllock = KeyEnum(71, 70);
  static const keyPause = KeyEnum(72, 119);
  static const keyInsert = KeyEnum(73, 110);
  static const keyHome = KeyEnum(74, 102);
  static const keyPageup = KeyEnum(75, 104);
  static const keyDelete = KeyEnum(76, 111);
  static const keyEnd = KeyEnum(77, 107);
  static const keyPagedown = KeyEnum(78, 109);
  static const keyRight = KeyEnum(79, 106);
  static const keyLeft = KeyEnum(80, 105);
  static const keyDown = KeyEnum(81, 108);
  static const keyUp = KeyEnum(82, 103);
  static const keyNumlock = KeyEnum(83, 69);
  static const keyKpslash = KeyEnum(84, 98);
  static const keyKpasterisk = KeyEnum(85, 55);
  static const keyKpminus = KeyEnum(86, 74);
  static const keyKpplus = KeyEnum(87, 78);
  static const keyKpenter = KeyEnum(88, 96);
  static const keyKp1 = KeyEnum(89, 79);
  static const keyKp2 = KeyEnum(90, 80);
  static const keyKp3 = KeyEnum(91, 81);
  static const keyKp4 = KeyEnum(92, 75);
  static const keyKp5 = KeyEnum(93, 76);
  static const keyKp6 = KeyEnum(94, 77);
  static const keyKp7 = KeyEnum(95, 71);
  static const keyKp8 = KeyEnum(96, 72);
  static const keyKp9 = KeyEnum(97, 73);
  static const keyKp0 = KeyEnum(98, 82);
  static const keyKpdot = KeyEnum(99, 83);
  static const key102nd = KeyEnum(100, 86);
  static const keyCompose = KeyEnum(101, 127);
  static const keyPower = KeyEnum(102, 116);
  static const keyKpequal = KeyEnum(103, 117);
  static const keyF13 = KeyEnum(104, 183);
  static const keyF14 = KeyEnum(105, 184);
  static const keyF15 = KeyEnum(106, 185);
  static const keyF16 = KeyEnum(107, 186);
  static const keyF17 = KeyEnum(108, 187);
  static const keyF18 = KeyEnum(109, 188);
  static const keyF19 = KeyEnum(110, 189);
  static const keyF20 = KeyEnum(111, 190);
  static const keyF21 = KeyEnum(112, 191);
  static const keyF22 = KeyEnum(113, 192);
  static const keyF23 = KeyEnum(114, 193);
  static const keyF24 = KeyEnum(115, 194);
  static const keyOpen = KeyEnum(116, 134);
  static const keyHelp = KeyEnum(117, 138);
  static const keyMenu = KeyEnum(118, 139);
  static const keyFront = KeyEnum(119, 132);
  static const keyStop = KeyEnum(120, 128);
  static const keyAgain = KeyEnum(121, 129);
  static const keyUndo = KeyEnum(122, 131);
  static const keyCut = KeyEnum(123, 137);
  static const keyCopy = KeyEnum(124, 133);
  static const keyPaste = KeyEnum(125, 135);
  static const keyFind = KeyEnum(126, 136);
  static const keyMute = KeyEnum(127, 113);
  static const keyVolumeup = KeyEnum(128, 115);
  static const keyVolumedown = KeyEnum(129, 114);
  static const keyKpcomma = KeyEnum(133, 121);
  static const keyRo = KeyEnum(135, 89);
  static const keyKatakanahiragana = KeyEnum(136, 93);
  static const keyYen = KeyEnum(137, 124);
  static const keyHenkan = KeyEnum(138, 92);
  static const keyMuhenkan = KeyEnum(139, 94);
  static const keyKpjpcomma = KeyEnum(140, 95);
  static const keyHangeul = KeyEnum(144, 122);
  static const keyHanja = KeyEnum(145, 123);
  static const keyKatakana = KeyEnum(146, 90);
  static const keyHiragana = KeyEnum(147, 91);
  static const keyZenkakuhankaku = KeyEnum(148, 85);
  static const keyKpleftparen = KeyEnum(182, 179);
  static const keyKprightparen = KeyEnum(183, 180);
  static const keyLeftctrl = KeyEnum(224, 29);
  static const keyShift = KeyEnum(225, 42);
  // KEY_LEFTSHIFT(225, 42);
  static const keyLeftalt = KeyEnum(226, 56);
  static const keyLeftmeta = KeyEnum(227, 125);
  static const keyRightctrl = KeyEnum(228, 97);
  static const keyRightshift = KeyEnum(229, 54);
  static const keyRightalt = KeyEnum(230, 100);
  static const keyRightmeta = KeyEnum(231, 126);
  static const keyPlaypause = KeyEnum(232, 164);
  static const keyStopcd = KeyEnum(233, 166);
  static const keyPrevioussong = KeyEnum(234, 165);
  static const keyNextsong = KeyEnum(235, 163);
  static const keyEjectcd = KeyEnum(236, 161);
  static const keyWww = KeyEnum(240, 150);
  static const keyBack = KeyEnum(241, 158);
  static const keyForward = KeyEnum(242, 159);
  static const keyScrollup = KeyEnum(245, 177);
  static const keyScrolldown = KeyEnum(246, 178);
  static const keyEdit = KeyEnum(247, 176);
  static const keySleep = KeyEnum(248, 142);
  static const keyScreenlock = KeyEnum(249, 152);
  static const keyRefresh = KeyEnum(250, 173);
  static const keyCalc = KeyEnum(251, 140);

  static const values = <KeyEnum>[RESERVED, keyA, keyAShift, keyB, keyBShift, keyC, keyCShift, keyD, keyDShift, keyE, keyEShift, keyF, keyFShift, keyG, keyGShift, keyH, keyHShift, keyI, keyIShift, keyJ, keyJShift, keyK, keyKShift, keyL, keyLShift, keyM, keyMShift, keyN, keyNShift, keyO, keyOShift, keyP, keyPShift, keyQ, keyQShift, keyR, keyRShift, keyS, keySShift, keyT, keyTShift, keyU, keyUShift, keyV, keyVShift, keyW, keyWShift, keyX, keyXShift, keyY, keyYShift, keyZ, keyZShift, key1, key1Shift, key2, key2Shift, key3, key3Shift, key4, key4Shift, key5, key5Shift, key6, key6Shift, key7, key7Shift, key8, key8Shift, key9, key9Shift, key0, key0Shift, keyEnter, keyEsc, keyBackspace, keyTab, keySpace, keyMinus, keyMinusShift, keyEqual, keyEqualShift, keyLeftbrace, keyLeftbraceShift, keyRightbrace, keyRightbraceShift, keyBackslash, keyBackslashShift, keySemicolon, keySemicolonShift, keyApostrophe, keyApostropheShift, keyGrave, keyGraveShift, keyComma, keyCommaShift, keyDot, keyDotShift, keySlash, keySlashShift, keyCapslock, keyF1, keyF2, keyF3, keyF4, keyF5, keyF6, keyF7, keyF8, keyF9, keyF10, keyF11, keyF12, keySysrq, keyScrolllock, keyPause, keyInsert, keyHome, keyPageup, keyDelete, keyEnd, keyPagedown, keyRight, keyLeft, keyDown, keyUp, keyNumlock, keyKpslash, keyKpasterisk, keyKpminus, keyKpplus, keyKpenter, keyKp1, keyKp2, keyKp3, keyKp4, keyKp5, keyKp6, keyKp7, keyKp8, keyKp9, keyKp0, keyKpdot, key102nd, keyCompose, keyPower, keyKpequal, keyF13, keyF14, keyF15, keyF16, keyF17, keyF18, keyF19, keyF20, keyF21, keyF22, keyF23, keyF24, keyOpen, keyHelp, keyMenu, keyFront, keyStop, keyAgain, keyUndo, keyCut, keyCopy, keyPaste, keyFind, keyMute, keyVolumeup, keyVolumedown, keyKpcomma, keyRo, keyKatakanahiragana, keyYen, keyHenkan, keyMuhenkan, keyKpjpcomma, keyHangeul, keyHanja, keyKatakana, keyHiragana, keyZenkakuhankaku, keyKpleftparen, keyKprightparen, keyLeftctrl, keyShift, keyLeftalt, keyLeftmeta, keyRightctrl, keyRightshift, keyRightalt, keyRightmeta, keyPlaypause, keyStopcd, keyPrevioussong, keyNextsong, keyEjectcd, keyWww, keyBack, keyForward, keyScrollup, keyScrolldown, keyEdit, keySleep, keyScreenlock, keyRefresh, keyCalc];

  final int code;
  final int linuxCode;
  final bool shift;

  const KeyEnum(this.code, this.linuxCode, [this.shift = false]);

  Map<String, dynamic> toJson() => {
    'linuxCode': linuxCode,
    'shift': shift,
  };

  /// Gets a [KeyEnum] from a given USB [code].
  factory KeyEnum.fromCode(int code, [bool shift = false]) => values.firstWhere((key) => key.code == code && key.shift == shift, orElse: () => null);

  /// Gets a [KeyEnum] from a given Linux [linuxCode].
  factory KeyEnum.fromLinuxCode(int linuxCode, [bool shift = false]) => values.firstWhere((key) => key.linuxCode == linuxCode && key.shift == shift, orElse: () => null);

  /// Gets the [KeyEnum] from a given JSON string. Example:
  /// ```json
  /// {
  ///     "linuxCode": 30,
  ///     "shift": false
  /// }
  /// ```
  factory KeyEnum.fromJson(Map<String, dynamic> json) => KeyEnum.fromLinuxCode(json['linuxCode'], json['shift'] ?? false);
}
